#include "spilling.h"

using namespace std;

/**
 * @brief Comparator function to sort vertices in descending order of their indegree.
 * 
 * Used to prioritize high-degree vertices as the primary candidates for register spilling,
 * following Chaitin's heuristic where spilling high-degree nodes eliminates the most interference.
 * 
 * @param a Pointer to the first vertex.
 * @param b Pointer to the second vertex.
 * @return true if vertex a has a strictly greater indegree than vertex b, false otherwise.
 */
bool cmp(Vertex<web> * a, Vertex<web> * b){
    if (a->getIndegree() > b->getIndegree()) return true;

    return false;
}

/**
 * @brief Generates the next lexicographical binary combination (grid) for spilling tracking.
 * 
 * Acts as a combinatorial generator mimicking a bitmask. Given an array representing 
 * nodes where '1' means "spilled" and '0' means "not spilled", this function shifts the active bits
 * to cycle through all possible combinations of selecting exactly `spilled` elements.
 * 
 * @param grid Reference to a binary vector tracking which candidates are selected to be spilled.
 * @param spilled The exact number of variables that must be marked as spilled simultaneously.
 * @return true if all combinations have been exhausted, false otherwise
 */
bool incrementGrid(vector<int>& grid, int spilled){
    if (spilled > (int)grid.size()) spilled = (int)grid.size();
    if (spilled == 0) return true;

    if (count(grid.begin(), grid.end(), 1) == 0){ 
        for (int i = 0; i < spilled; i++){
            grid[i] = 1;
        }
        return false;
    }

    bool moved = false;
    for (int i = 0; i < (int)grid.size()-1; i++){
        if (grid[i+1] == 1) {continue;}
        if (grid[i] == 1){
            moved = true;
            grid[i] = 0;
            grid[i+1] = 1;
            int counter = 0;
            for (int j = 0; j < i; j++){
                if (grid[j] == 1) {counter++;}
                grid[j] = 0;
            }
            for (int k = 0; k < counter; k++){
                grid[k] = 1;
            }
            break;
        }
    }
    return !moved;
}

/**
 * @brief Evaluates whether any combination of a specific spill count yields a valid coloring.
 * 
 * Iterates through combinations generated by 'incrementGrid' for a set number of spills. 
 * Temporarily flags the chosen candidates as 'visited' (ignored) and attempts to color the 
 * remaining subgraph. It returns true as soon as a working subset is identified.
 * 
 * @param g Pointer to the interference graph.
 * @param info Struct holding algorithm settings, limits, and user choices.
 * @param candidates List of the highest-degree vertices considered for spilling.
 * @param coloring Function that will execute the coloring of the graph.
 * @param spilled The number of nodes to spill during this test.
 * @return true if at least one combination allows the remaining graph to fit within the register limit, false otherwise.
 */
bool attempt(Graph<web>* g, params info, vector<Vertex<web> *> candidates, function<int(Graph<web>* g, int)> coloring, int spilled){
    if (spilled == 0){
        for (auto &v : g->getVertexSet()) v->setVisited(false);
        
        return coloring(g, info.regs) <= info.regs;
    }

    if (spilled > (int)candidates.size()) return false;

    vector<int> grid((int)candidates.size(), 0);

    while (!incrementGrid(grid, spilled)){
        for (auto &v : g->getVertexSet()) v->setVisited(false);

        for (int i = 0; i < (int)grid.size(); i++){
            if (grid[i] == 1){
                candidates[i]->setVisited(true);
            }
        }

        if (coloring(g, info.regs) <= info.regs) return true;
    }

    return false;    
}

/**
 * @brief FInds and applies the absolute best subset configuration for the chosen spill count.
 * 
 * Once the optimal spill number is computed via binary search, this function runs through multiple 
 * different combinations to locate the one that minimizes the overall number of colors used 
 * ('bestNum'). It commits this optimized configuration back onto the graph and executes the final coloring.
 * 
 * @param g Pointer to the interference graph.
 * @param info Struct holding algorithm settings, limits, and user choices.
 * @param candidates List of the highest-degree vertices considered for spilling.
 * @param coloring Function that will execute the coloring of the graph.
 * @param spilled The calculated number of spills determined to be necessary and sufficient.
 */
void finalSpill(Graph<web>* g, params info, vector<Vertex<web> *> candidates, function<int(Graph<web>* g, int)> coloring, int spilled){
    if (spilled == 0){
        for (auto &v : g->getVertexSet()) v->setVisited(false);
        coloring(g, info.regs);
        return;
    }

    int bestNum = numeric_limits<int>::max();
    vector<int> bestOrder;
    vector<int> grid((int)candidates.size(), 0);

    while (!incrementGrid(grid, spilled)){
        for (auto &v : g->getVertexSet()) v->setVisited(false);

        for (int i = 0; i < (int)grid.size(); i++){
            if (grid[i] == 1) candidates[i]->setVisited(true);
        }

        int newNum = coloring(g, info.regs);
        if (newNum < bestNum){
            bestNum = newNum;
            bestOrder = grid;
        }
    }

    for (auto &v : g->getVertexSet()) v->setVisited(false);
    for (int i = 0; i < (int)bestOrder.size(); i++){
        if (bestOrder[i] == 1) candidates[i]->setVisited(true);
    }
    coloring(g, info.regs);
}

struct result spill(Graph<web>* g, params info, function<int(Graph<web>* g, int)> coloring){

  /*
   if (graphColoringBasic(g, info.regs) != -1){
        struct result res = build(g, info);
        return res;
    }*/

    printf("total regs: %d",info.regs);

    vector<Vertex<web> *> vSet = g->getVertexSet();
    sort(vSet.begin(), vSet.end(), cmp);

    // X is the number of 'best' candidates the program will use to try to find the optimal spill. The more candidates, the better the result, but also the longer the program will take to run (exponentially in the number of candidates). It is recommended to set it to a value between 15 and 25.
    int X = 20; 
    vector<Vertex<web> *> candidates;
    for(int i = 0; i < (int)vSet.size() && i < X; i++) {
        candidates.push_back(vSet[i]);
    }

    int maxPossible = min((int)candidates.size(), info.alg.val);
    vector<int> allSpills(maxPossible + 1);
    for (int i = 0; i < (int)allSpills.size(); i++) allSpills[i] = i;

    auto it = lower_bound(allSpills.begin(), allSpills.end(), true,
        [&](int spilled, bool target) {
            return !attempt(g, info, candidates, coloring, spilled);
        }
    );

    int trueSpills = (it != allSpills.end()) ? *it : -1;

    if (trueSpills != -1){
        finalSpill(g, info, candidates, coloring, trueSpills);
    } else {
        finalSpill(g, info, candidates, coloring, 0);
    }

    struct result res = build(g, info);
    if (trueSpills == -1) res.possible = false;
    return res;
}